services:
  redlib:
#    image: quay.io/redlib/redlib:latest
# Temp fix since Redlib broke
    image: ghcr.io/cycneuramus/containers:redlib
    restart: always
    container_name: "redlib"
    ports:
      - 8677:8080 # Specify `127.0.0.1:8080:8080` instead if using a reverse proxy
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
      # - seccomp=seccomp-redlib.json
    cap_drop:
      - ALL
    env_file: .env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
