services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    ports:
      - '8870:8080'
    volumes:
      - ${DATA_PATH}/StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ${DATA_PATH}/StirlingPDF/extraConfigs:/configs
      - ${DATA_PATH}/StirlingPDF/customFiles:/customFiles/
      - ${DATA_PATH}/StirlingPDF/logs:/logs/
      - ${DATA_PATH}/StirlingPDF/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
